apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-pod-replica-set  
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 3
  selector:
    matchLabels:
      name: hello-pod
  template:
    metadata:
      name: hello-pod
      labels:
        name: hello-pod
    spec:
      containers:
      - name: python-api
        image: pwlodek/python-api
        resources:
          requests:
            cpu: 100m
            memory: 100Mi        
        ports:
        - containerPort: 80 # kubectl expose rs hello-pod-replica-set --name myservicefromrs --target-port=80 --type=NodePort