apiVersion: v1
kind: Service
metadata:
  name: hello-pod-service
  labels:
    app: my-service
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    name: hello-pod